#!/usr/bin/env python3
"""Lift the committed joint-fit JSONs into the trusted/untrusted summary table.

Reads the in-repo `joint_json/*_joint_fit.json` (sibling dir) and writes
`results/joint_fit_summary.md`. Both the source JSONs and this generator are
committed, so the summary is reproducible from a clean checkout:

    python analysis/scattering-refit-2026-06/gen_joint_summary.py

Trust is a HUMAN verdict (4-lens adversarial workflow wf_417320dd, 2026-06-19),
NOT mechanically derived from log-evidence. The mechanical columns (railed,
unconstrained) are supporting evidence only.
"""

import glob
import json
from pathlib import Path

JOINT_DIR = Path(__file__).parent / "joint_json"
OUT = Path(__file__).resolve().parents[2] / "results" / "joint_fit_summary.md"

# Explicit human verdict — see flits-joint-fit-shallow-alpha memory.
TRUST = {
    "johndoeII": "trusted",
    "wilhelm": "trusted",
    "phineas": "trusted",
    "oran": "refuted",
}  # all others: unadjudicated
REASON = {
    "johndoeII": "4-lens adversarial verify; sub-Kolmogorov α survives α=4 rejection at Δ(−2lnL)≈2400",
    "wilhelm": "4-lens adversarial verify; tight, clean",
    "phineas": "4-lens adversarial verify; tight",
    "oran": "REFUTED — CHIME ζ_C unconstrained/railed; α is not a measurement",
    "chromatica": "α railed at upper bound (6.0) → not a measurement",
    "freya": "α railed at upper bound (6.0) → not a measurement",
    "hamilton": "α railed at upper bound (6.0) → not a measurement",
    "isha": "α unconstrained (σ ≈ 2.6) → not a measurement",
    "mahi": "α near upper rail (5.53), wide posterior → not a measurement",
    "whitney": "shallow α=1.46 but NOT adversarially verified; pending multicomponent refit",
    "zach": "tight α but anomalous lnZ (~−1.7e5); pending multicomponent refit",
}


def rows():
    for f in sorted(glob.glob(str(JOINT_DIR / "*_joint_fit.json"))):
        d = json.load(open(f))
        b = d["burst"]
        a, t = d["alpha"], d["tau_1ghz"]
        lo, hi = d.get("alpha_bounds", [1.0, 6.0])
        railed = min(abs(a["median"] - lo), abs(a["median"] - hi)) < 0.05
        unconstrained = max(a["err_plus"], a["err_minus"]) > 0.5
        yield {
            "burst": b,
            "alpha": a["median"],
            "a_ep": a["err_plus"],
            "a_em": a["err_minus"],
            "tau": t["median"],
            "lnZ": d.get("log_evidence", float("nan")),
            "railed": railed,
            "unconstrained": unconstrained,
            "trust": TRUST.get(b, "unadjudicated"),
            "reason": REASON.get(b, ""),
        }


def render() -> str:
    """Build the summary markdown from the committed JSONs (no side effects)."""
    rs = sorted(rows(), key=lambda r: {"trusted": 0, "unadjudicated": 1, "refuted": 2}[r["trust"]])
    trusted = [r for r in rs if r["trust"] == "trusted"]
    L = []
    L.append("# CHIME+DSA joint scattering-fit summary")
    L.append("")
    L.append(
        "Per-sightline shared (τ₁GHz, α) from the joint CHIME+DSA fit "
        "(`scattering/scat_analysis/burstfit_joint.py`). Source results: "
        "`analysis/scattering-refit-2026-06/joint_json/` (committed)."
    )
    L.append("")
    L.append("## ⚠️ Trust: only 3 of 11 fits are trustworthy")
    L.append("")
    L.append(
        f"**Trusted (use): {', '.join(r['burst'] for r in trusted)}** — verified via a 4-lens "
        "adversarial workflow (wf_417320dd, 2026-06-19). Trusted α span **1.37→3.58** "
        "(johndoeII is genuinely sub-Kolmogorov)."
    )
    L.append("")
    L.append(
        "**Do NOT cite the other 8.** Trust is a human adversarial verdict, *not* derived from "
        "log-evidence. Most other sources rail α at the upper bound (6.0), are unconstrained, or "
        "are unadjudicated pending the multicomponent hidden-pulse refit. `oran` is explicitly "
        "refuted (CHIME nuisance railed). A tight error bar alone (e.g. whitney, zach) does NOT "
        "imply trust."
    )
    L.append("")
    L.append("| burst | trust | α | τ₁GHz (ms) | lnZ | railed | unconstrained | reason |")
    L.append("|---|---|---|---|---|---|---|---|")
    badge = {"trusted": "✅ trusted", "refuted": "❌ refuted", "unadjudicated": "⏳ unadjudicated"}
    for r in rs:
        L.append(
            f"| {r['burst']} | {badge[r['trust']]} | "
            f"{r['alpha']:.2f} +{r['a_ep']:.2f}/−{r['a_em']:.2f} | {r['tau']:.4f} | "
            f"{r['lnZ']:.0f} | {'yes' if r['railed'] else '—'} | "
            f"{'yes' if r['unconstrained'] else '—'} | {r['reason']} |"
        )
    L.append("")
    L.append(
        "_Generated by `analysis/scattering-refit-2026-06/gen_joint_summary.py` from the "
        "committed joint-fit JSONs. Regenerate after any refit._"
    )
    return "\n".join(L) + "\n"


def main():
    text = render()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
