chunk_size: 2000
diagnostics: true
dlogz: 0.5
dm_init: 0.0
extend_chain: true
f_factor: 16
fitting_method: nested
max_chunks: 5
model_scan: true
nlive: 400
nlive_walks: 15
nproc: 8
outer_trim: 0.15
onpulse_pad_factor: 0.5
path: /Users/jakobfaber/Data/Faber2026/dsa110/DSA_bursts/hamilton_chime_I_518_8007_32000b_cntr_bpc.npy
plot: true
sampcfg_path: /Users/jakobfaber/Developer/repos/github.com/jakobtfaber/Faber2026/pipeline/scattering/configs/sampler.yaml
steps: 10000
t_factor: 24
telcfg_path: /Users/jakobfaber/Developer/repos/github.com/jakobtfaber/Faber2026/pipeline/scattering/configs/telescopes.yaml
telescope: chime
