chunk_size: 2000
diagnostics: true
dm_init: 0.0
extend_chain: true
f_factor: 64
max_chunks: 5
model_scan: true
nproc: 16
path: /arc/home/jfaber/baseband_morphologies/chime_dsa_codetections/data/DSA_bursts/johndoeII_chime_I_696_5184_32000b_cntr_bpc.npy
plot: true
steps: 10000
t_factor: 24
telescope: chime
