#!/usr/bin/env python
"""Render tab:beta rows for Faber2026 from beta_campaign_verdicts.json (Phase 9).

Emits beta_table_rows.tex beside this script: one deluxetable data row per
graded burst, rail-aware --

  interior   : beta median +/- percentiles; alpha = 2b/(b-2) with propagated
               errors from the fit JSON's derived-alpha posterior
  railed-hi  : the posterior is pinned at the beta=4 square-law bound; beta is
               quoted as a limit (>= median at 3-sigma/edge-mass evidence) and
               alpha as "4 (limit)" -- exponential-consistent, not a
               measurement (ADR-0004 rail rule; ADR-0007 re-open candidate)
  FAIL rows  : excluded, listed in a trailing comment

The caption/tablenotes live in the manuscript shell (Faber2026 beta_table.tex,
cb89878); this exporter provides only the \\startdata block so table values
stay pipeline-derived.

  conda run -n flits python analysis/beta_campaign/export_beta_table.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RUNS = Path(os.environ.get("FLITS_RUNS", "/Users/jakobfaber/Developer/scratch/flits-local-runs"))
sys.path.insert(0, str(REPO))

from scattering.scat_analysis.burst_metadata import load_tns_name  # noqa: E402

CXD = {
    "_sharedzeta": r"$1\times1$",
    "_C1D1": r"$1\times1$",
    "_C2D1": r"$2\times1$",
    "_C2D2": r"$2\times2$",
    "_C2D4_cwin": r"$2\times4$",
    "_C3D3": r"$3\times3$",
}


def _tns(burst: str) -> str:
    name = load_tns_name(burst.removesuffix("_fine"))
    return name or burst


def _alpha_cell(burst: str, suffix: str, railed: bool) -> str:
    if railed:
        return r"$4$ (limit)"
    fit = json.loads((RUNS / "data/joint" / f"{burst}_joint_fit{suffix}.json").read_text())
    a = fit["alpha"]
    return rf"${a['median']:.2f}^{{+{a['err_plus']:.2f}}}_{{-{a['err_minus']:.2f}}}$"


def main() -> int:
    verdicts = json.loads((Path(__file__).parent / "beta_campaign_verdicts.json").read_text())
    rows, excluded = [], []
    for r in verdicts["rows"]:
        if r["final"] == "FAIL":
            excluded.append(f"{r['burst']} (gate FAIL: {r['reason'].split(';')[0]})")
            continue
        # railed-hi is the physical square-law boundary member (quotable as a
        # limit); railed-lo (beta=3 prior edge, alpha=6 ceiling) and
        # unconstrained (mass at both bounds) are NOT citable rows.
        if r["rail_class"] in ("railed-lo", "unconstrained"):
            excluded.append(f"{r['burst']} ({r['rail_detail']['detail']})")
            continue
        railed = r["rail_class"] == "railed-hi"
        b, (em, ep) = r["beta"], r["beta_err"]
        beta_cell = (
            r"$\to 4$\tablenotemark{d}" if railed else rf"${b:.3f}^{{+{ep:.3f}}}_{{-{em:.3f}}}$"
        )
        cc = f"{r['chi2_chime']:.2f}" if r["chi2_chime"] is not None else r"\nodata"
        cd = f"{r['chi2_dsa']:.2f}" if r["chi2_dsa"] is not None else r"\nodata"
        rows.append(
            f"{_tns(r['burst'])} & {CXD[r['suffix']]} & {beta_cell} & "
            f"{_alpha_cell(r['burst'], r['suffix'], railed)} & "
            f"${r['tau']:.3g}$ & {cc}/{cd} \\\\"
        )
    out = Path(__file__).parent / "beta_table_rows.tex"
    lines = [
        "% Generated by analysis/beta_campaign/export_beta_table.py from",
        "% beta_campaign_verdicts.json -- do not hand-edit values.",
        *rows,
    ]
    if excluded:
        lines.append(f"% excluded (not citable): {'; '.join(excluded)}")
    if verdicts["missing"]:
        lines.append(f"% missing campaign fits: {', '.join(verdicts['missing'])}")
    out.write_text("\n".join(lines) + "\n")
    print(f"[export] wrote {out} ({len(rows)} rows, {len(excluded)} excluded)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
