"""One-off: add the figure batch to the manifest + review records (safe JSON escaping)."""

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
man_p = REPO / "results" / "figures.manifest.json"
rev_p = REPO / "results" / "figures.review.json"

BATCH = {
    "tau_nu_ladder.png": {
        "source": "analysis/scattering-refit-2026-06/dsa_figs/tau_nu_ladder.png",
        "dest": "tau_nu_ladder.png",
        "section": "sections/results.tex",
        "title": "Joint-fit tau(nu) scattering-index ladder",
        "expectation": "Single panel, log-y tau(nu) [ms] vs frequency 0.4-1.6 GHz, ~11 colored curves each legend-labeled with a per-burst alpha, 68% shaded credible bands, CHIME (0.4-0.8) and DSA (~1.3-1.55 GHz) bands shaded grey; alphas span the lower rail (~1.37-1.46) through ~3.6 up to the upper rail (6.00).",
        "caption": r"Joint-fit pulse-broadening ladder $\tau(\nu)=\tau_{1\,\mathrm{GHz}}(\nu/1\,\mathrm{GHz})^{-\alpha}$ for the co-detected bursts with $68\%$ credible bands, spanning the CHIME ($0.4$--$0.8\,\mathrm{GHz}$) and DSA-110 ($1.3$--$1.5\,\mathrm{GHz}$) bands whose ${\sim}1\,\mathrm{GHz}$ separation sets the lever arm on $\alpha$. The inferred indices range from the lower prior rail ($\alpha\!\to\!1.4$, marginal or multi-component bursts) to the upper rail ($\alpha\!\to\!6$); only the well-constrained single-screen sightlines yield trustworthy intermediate values, consistent with the rail behaviour discussed in this section. Generated by the \texttt{dsa110-FLITS} pipeline.",
    },
    "joint_ppc_montage.png": {
        "source": "analysis/scattering-refit-2026-06/dsa_figs/joint_ppc_montage.png",
        "dest": "joint_ppc_montage.png",
        "section": "sections/results.tex",
        "title": "Joint CHIME-DSA posterior predictive checks",
        "expectation": "4 rows x 2 cols (CHIME left, DSA right) for bursts johndoeII/oran/wilhelm/phineas; each panel black data + red joint model overlaid, per-row title with shared alpha + tau_1GHz, per-panel reduced chi2 annotations (~1.0-2.0).",
        "caption": r"Joint CHIME--DSA posterior predictive checks for the four bursts with simultaneous two-band fits (nicknames johndoeII, oran, wilhelm, phineas): band-integrated profile (black) versus joint model (red) in each telescope, annotated with the shared $\alpha$, $\tau_{1\,\mathrm{GHz}}$, and per-band reduced $\chi^2$. Near-white residuals ($\chi^2_\nu\approx1$) show that a single shared-$\alpha$ model reproduces both bands simultaneously. Generated by the \texttt{dsa110-FLITS} pipeline.",
    },
    "chime_subband_compare.png": {
        "source": "analysis/scattering-refit-2026-06/dsa_figs/chime_subband_compare.png",
        "dest": "chime_subband_compare.png",
        "section": "sections/budget.tex",
        "title": "CHIME sub-band profile comparison",
        "expectation": "2 columns (johndoeII, wilhelm) x 4 CHIME sub-bands (0.400-0.480, 0.507-0.587, 0.614-0.694, 0.720-0.800 GHz); each panel a profile time series (ms) annotated with w_rms and w_tail; wilhelm's top 0.40-0.48 GHz panel is empty (nan, flat line).",
        "caption": r"CHIME sub-band profiles for FRBs johndoeII and wilhelm across four $80\,\mathrm{MHz}$ sub-bands ($0.40$--$0.80\,\mathrm{GHz}$), annotated with the rms width $w_{\mathrm{rms}}$ and tail timescale $w_{\mathrm{tail}}$. The frequency evolution of the profile shape (and the data-empty $0.40$--$0.48\,\mathrm{GHz}$ sub-band for wilhelm) is the diagnostic used to flag unmodeled sub-components before a scattering index is quoted. Generated by the \texttt{dsa110-FLITS} pipeline.",
    },
}

REVIEW = {
    "tau_nu_ladder.png": "Independent read. Single axes, suptitle 'Joint-fit tau(nu)=tau_1GHz nu^-alpha ladder (68% band)'. log-y tau(nu) ms vs frequency 0.4-1.6 GHz. ~11 colored curves with shaded 68% bands; legend lists per-burst alpha: chromatica 6.00, freya 6.00, hamilton 5.99, isha 5.05, johndoeII 1.37, mahi 5.53, oran 1.43, phineas 3.58, whitney 1.46, wilhelm 2.71, zach 3.66. CHIME and DSA bands shaded grey. Several alpha at the prior rails (6.0 ceiling / ~1.4 floor) -- matches the manifest's honest framing. Axes sane, no artifacts. Matches expectation.",
    "joint_ppc_montage.png": "Independent read. 4x2 grid, CHIME left / DSA right, rows johndoeII/oran/wilhelm/phineas. Black data + red joint model overlaid in each. Row titles carry shared alpha + tau_1GHz; per-panel reduced chi2 annotated (johndoeII 1.14/1.03, oran 1.11/1.06, wilhelm 1.71/1.30, phineas 1.20/2.02). Models track the pulse + tail; residuals near-white. phineas DSA chi2=2.02 is the most marginal but visually reasonable. Matches expectation.",
    "chime_subband_compare.png": "Independent read. 2 columns (johndoeII, wilhelm) x 4 CHIME sub-bands. Profile time series (ms) with w_rms / w_tail annotations per panel. johndoeII shows a clear scattered pulse narrowing across sub-bands; wilhelm's top 0.40-0.48 GHz panel is empty (w_rms=nan, flat line) as expected for absent data, lower sub-bands show the pulse. No artifacts. Matches expectation.",
}

man = json.loads(man_p.read_text())
for k, v in BATCH.items():
    man[k] = v
man_p.write_text(json.dumps(man, indent=2) + "\n")

rev = json.loads(rev_p.read_text())
have = {x["path"] for x in rev["verdicts"]}
for path, notes in REVIEW.items():
    if path not in have:
        rev["verdicts"].append({"path": path, "verdict": "match", "notes": notes})
rev_p.write_text(json.dumps(rev, indent=2) + "\n")

print("manifest entries:", list(man))
print("review verdicts:", [x["path"] for x in rev["verdicts"]])
